const UPDATE_USERNAME = 'UPDATE_USERNAME'
const UPDATE_NICKNAME = 'UPDATE_NICKNAME'
const UPDATE_PROFILE_URL = 'UPDATE_PROFILE_URL'
const UPDATE_COVER_URL = 'UPDATE_COVER_URL'

export { UPDATE_USERNAME, UPDATE_NICKNAME, UPDATE_PROFILE_URL, UPDATE_COVER_URL }